//
//  SpotifyArtistFactory.m
//  YapTap
//
//  Created by Jon Deokule on 5/2/15.
//  Copyright (c) 2015 Appcoda. All rights reserved.
//

#import "SpotifyArtistFactory.h"

@implementation SpotifyArtistFactory

+ (NSArray *) artistsForCategory:(NSString *)category
{
    if ([category  isEqual: @"Random"]) {
        return @[@"A Thousand Horses",
                 @"Andy Grammer",
                 @"Ariana Grande",
                 @"Big Sean",
                 @"Billy Currington",
                 @"Blake Shelton",
                 @"Brad Paisley",
                 @"Brantley Gilbert",
                 @"Bruno Mars",
                 @"Calvin Harris",
                 @"Canaan Smith",
                 @"Carly Rae Jepsen",
                 @"Carrie Underwood",
                 @"Chedda Da Connect",
                 @"Chris Brown",
                 @"Ciara",
                 @"Cole Swindell",
                 @"David Guetta",
                 @"Dierks Bentley",
                 @"Dillon Francis",
                 @"Dj Snake",
                 @"Drake",
                 @"Easton Corbin",
                 @"Echosmith",
                 @"Ed Sheeran",
                 @"Ellie Goulding",
                 @"Eminem",
                 @"Eric Church",
                 @"Eric Paslay",
                 @"Fall Out Boy",
                 @"Fetty Wap",
                 @"Fifth Harmony",
                 @"Flo Rida ",
                 @"Florida Georgia Line",
                 @"Future",
                 @"George Ezra",
                 @"Hozier",
                 @"J. Cole",
                 @"Jason Aldean ",
                 @"Jason Derulo",
                 @"Jennifer Lopez",
                 @"Josh Groban",
                 @"Justin Bieber",
                 @"Justin Timberlake",
                 @"Kanye West",
                 @"Keith Urban",
                 @"Kelly Clarkson",
                 @"Kelsea Ballerini",
                 @"Kendrick Lamar",
                 @"Kenny Chesney",
                 @"Kevin Gates",
                 @"Kid Ink",
                 @"Little Big Town",
                 @"Linkin Park",
                 @"Luke Bryan",
                 @"Major Lazer",
                 @"Mariah Carey",
                 @"Mark Ronson",
                 @"Maroon 5",
                 @"Martin Garrix",
                 @"Meghan Trainor",
                 @"Mumford & Sons",
                 @"Natalie La Rose",
                 @"Nate Ruess",
                 @"Ne-Yo",
                 @"Nick Jonas",
                 @"Nicki Minaj",
                 @"Nicky Jam",
                 @"Omarion ",
                 @"Omi",
                 @"One Direction",
                 @"One Republic",
                 @"Pharrell Williams",
                 @"Pitbull ",
                 @"Psy",
                 @"Rachel Platten",
                 @"Rae Sremmurd",
                 @"Red Hot Chili Peppers",
                 @"Rich Homie Quan",
                 @"Rihanna",
                 @"Sam Hunt",
                 @"Sam Smith",
                 @"Sawyer Fredericks",
                 @"Sheppard",
                 @"Sia",
                 @"Silento",
                 @"Skrillex & Diplo",
                 @"T-Wayne",
                 @"Taylor Swift",
                 @"The Weekend",
                 @"Tim Mcgraw",
                 @"Tori Kelly",
                 @"Tove Lo",
                 @"Trey Songz",
                 @"Twenty One Pilots",
                 @"Tyler Farr",
                 @"Wale",
                 @"Walk The Moon",
                 @"Wiz Khalifa",
                 @"X Ambassadors",
                 @"Zac Brown Band",
                 @"Zedd",
                 @"Beyonce",
                 @"Katy Perry",
                 @"Imagine Dragons",
                 @"Charlie Puth",
                 @"My Morning Jacket",
                 @"Chris Stapleton",
                 @"Selena Gomez",
                 @"Alabama Shakes",
                 @"Nirvana",
                 @"Jeremih",
                 @"Britney Spears",
                 @"Lee Brice",
                 @"Vance Joy",
                 @"Adele",
                 @"Darius Rucker",
                 @"Michael Jackson",
                 @"Romeo Santos",
                 @"Miguel",
                 @"Miranda Lambert",
                 @"Miley Cyrus",
                 @"Shawn Mendes",
                 @"Madonna",
                 @"Backstreet Boys",
                 @"Elvis Presley",
                 @"Elton John",
                 @"Lady Gaga",
                 @"U2",
                 @"Coldplay",
                 @"Black Eyed Peas",
                 @"R Kelly",
                 @"Usher",
                 @"Steve Aoki",
                 @"Bruce Springsteen",
                 @"Avicii",
                 @"Tiesto",
                 @"Nelly",
                 
                 @"Addams Family Theme",
                 @"Aladdin Theme",
                 @"Back To The Future Theme",
                 @"Batman Theme",
                 @"Baywatch",
                 @"Brady Bunch Theme",
                 @"Breakfast Club",
                 @"Breaking Bad Theme",
                 @"Bugs Bunny",
                 @"Chanukah Song",
                 @"Dexter Theme",
                 @"Family Guy Theme",
                 @"Fresh Prince",
                 @"Game of Thrones",
                 @"Gilligan's Island",
                 @"Hannah Montana",
                 @"Home Alone Theme",
                 @"Indiana Jones Theme",
                 @"Inspector Gadget Theme",
                 @"James Bond Theme",
                 @"Kill Bill Theme",
                 @"Lion King",
                 @"Lost Main Theme",
                 @"Macgyver",
                 @"Mission Impossible",
                 @"Ninja Turtles Theme",
                 @"Pretty Woman",
                 @"Saved By The Bell Theme",
                 @"Seinfeld Theme",
                 @"Sex and The City TV",
                 @"The Simpsons",
                 @"SpongeBob Theme",
                 @"Star Trek Theme",
                 @"Star Wars Theme",
                 @"Superman Theme",
                 @"The Flinstones Rhymes",
                 @"The Godfather",
                 @"Titanic",
                 
                 @"Weird Al Yankovic",
                 @"Touch Your Boobies",
                 @"Sir Mix A Lot",
                 @"Show Me Your Genitals",
                 @"Shave Your Ballsack",
                 @"Sarah Silverman Poop",
                 @"Robin Williams Fires",
                 @"Robin Williams Drugs",
                 @"Robin Williams Bush",
                 @"Red Peters Bonus",
                 @"Monty Python Penis ",
                 @"Monty Python Sit On My Face ",
                 @"Louis C.K. Taking Sexual ",
                 @"Louis C.K. Pets",
                 @"Loser Hip Hop Ringtone",
                 @"Knock Knock Jokes",
                 @"Keep It In Your Pants",
                 @"Justin Bieber Farts",
                 @"Jerky Boys Laser Surgery",
                 @"I'm On A Boat",
                 @"I Think I Farted",
                 @"I Just Had Sex",
                 @"I Don't Fuck With You",
                 @"Guys They Just Wanna",
                 @"Google That Shit",
                 @"Fart Sounds",
                 @"Everyone Else Is An Asshole",
                 @"Eddie Murphy Skeleton In Closet",
                 @"Eddie Griffin Tiger Woods",
                 @"Coffee Makes Me Poo",
                 @"Chris Rock Rap",
                 @"Chris Rock Drugs",
                 @"Chris Rock Don't Cheat",
                 @"Ching Chang Chong ",
                 @"Bo Burnham God",
                 @"Bo Burnham Brain",
                 @"Bad Sex Taryn ",
                 @"Aziz Ansari Girls",
                 @"Amy Schumer Cockblock",
                 @"99 Words For Boobs",
                 @"Red Peters Vagina "
                 ];
    } else {
        return @[@"Error"];
    }

    return @[];
}

@end
