//
//  SpotifyArtistFactory.m
//  YapTap
//
//  Created by Jon Deokule on 5/2/15.
//  Copyright (c) 2015 Appcoda. All rights reserved.
//

#import "SpotifyArtistFactory.h"

@implementation SpotifyArtistFactory

+ (NSArray *) artistsForCategory:(NSString *)genre
{
    if ([genre  isEqual: @"Pop"]) {
        return @[@"Abba",
                 @"Adam Lambert",
                 @"Adele",
                 @"Amy Winehouse",
                 @"Andreas Roffler",
                 @"Ariana Grande",
                 @"Ark Patrol",
                 @"Astronauts",
                 @"Backstreet Boys",
                 @"Bastille",
                 @"Beth Love",
                 @"Beyonce",
                 @"Big Sean",
                 @"Blackbear",
                 @"Blue October",
                 @"Brayton Bowman",
                 @"Britney Spears",
                 @"Broken Back",
                 @"Bruce Springsteen",
                 @"Bruno Mars",
                 @"Cashmere Cat",
                 @"Charlie Puth",
                 @"Christina Aguilera",
                 @"Christina Perri",
                 @"Coldpay",
                 @"Darius",
                 @"Dawin",
                 @"Devon Baldwin",
                 @"Dj Earworm",
                 @"Dj Midnight",
                 @"Duran Duran",
                 @"Eagles",
                 @"Ed Sheeran",
                 @"Ellie Goulding",
                 @"Elton John",
                 @"Elvis Presley",
                 @"Fantasia",
                 @"Fergie",
                 @"Glee",
                 @"Halvorsen",
                 @"Honne",
                 @"Hozier",
                 @"Hyphy Da Spider",
                 @"I Love Makonnen",
                 @"I Prevail",
                 @"Idina Menzel",
                 @"Jack Ü",
                 @"Janet Jackson",
                 @"Jennifer Lopez ",
                 @"Jessie J",
                 @"John Legend",
                 @"Josh Groban",
                 @"Justin Bieber",
                 @"Kaskade",
                 @"Katy Perry",
                 @"Lady Gaga",
                 @"Madonna",
                 @"Manganas Garden",
                 @"Mariah Carey",
                 @"Mark Ronson",
                 @"Maroon 5",
                 @"Marvin Gaye 50",
                 @"Max Feat Hoodie",
                 @"Meghan Trainor",
                 @"Michael Jackson",
                 @"Miley Cyrus",
                 @"Nick Jonas",
                 @"Nsync",
                 @"Oh Wonder",
                 @"One Direction",
                 @"Penguin Prison",
                 @"Pet Shop Boys",
                 @"Phoebe Ryan",
                 @"Pitbull Chris Brown",
                 @"Prince",
                 @"Psy",
                 @"R Kelly",
                 @"Rae Sremmurd",
                 @"Rihanna",
                 @"Robbie Williams",
                 @"Sam Cooke",
                 @"Sam Smith",
                 @"Selena Gomez",
                 @"Shawn Mendes",
                 @"Sia",
                 @"Simon And Garfunkel",
                 @"Skrillex",
                 @"Spice Girls",
                 @"Sterkol",
                 @"Steve Aoki",
                 @"Stevie Wonder",
                 @"Take Me To Chruch",
                 @"Tep No",
                 @"The Beatles",
                 @"The Black Eyed Peas",
                 @"The Drums",
                 @"The Eden Project",
                 @"The Weekend",
                 @"Tove Lo",
                 @"Trevor Wesley",
                 @"U2",
                 @"Whitney Houston",
                 @"Xylo",
                 @"Zyan Malik"
                 ];
    } else if ([genre  isEqual: @"TV/Film"]) {
        return @[@"The Rocky Horror Picture Show",
                 @"100 Movie Themes",
                 @"24 Main Theme",
                 @"300 Soundtrack",
                 @"Aladdin Theme",
                 @"Austin Powers Theme",
                 @"Back To The FutureTheme",
                 @"Batman Theme",
                 @"Baywatch",
                 @"Beverly Hills 90210",
                 @"Beverly Hills Cop Theme",
                 @"Bill Conti ",
                 @"Breakfast Club",
                 @"Breaking Bad Theme",
                 @"Bugs Bunny",
                 @"Call Of Duty",
                 @"Chanukah Song",
                 @"Columbo Theme",
                 @"Dallas",
                 @"Dexter Theme",
                 @"Django",
                 @"Doctor Who Theme",
                 @"E.T Theme",
                 @"Family Guy Main Theme",
                 @"Family Matters Theme",
                 @"Fifa",
                 @"Free Willy",
                 @"Fresh Prince Of Bel-Air ",
                 @"Game Of Thrones Main Theme",
                 @"Ghostbusters Dance",
                 @"Hannah Montana Theme",
                 @"Hilarious Hit Makers - Muppet Show",
                 @"Home Alone Theme",
                 @"Hooked Of A Feeling",
                 @"I’Ll Be There For You",
                 @"Indiana Jones Theme",
                 @"Inspector Gadget Theme",
                 @"James Bond Skyfall",
                 @"James Bond Theme",
                 @"Jaws Theme",
                 @"Kill Bill",
                 @"Kill Bill Whistle Theme",
                 @"Law And Order Theme",
                 @"Lion King",
                 @"Lost Main Theme",
                 @"Love Boat Theme",
                 @"Mac Gyver Main Theme",
                 @"Mission Impossible",
                 @"Monday Night Football Theme",
                 @"Nba Espn",
                 @"Patton Theme",
                 @"Peanuts Theme",
                 @"Pinky And The Brain Theme",
                 @"Pirates Of The Caribbean Theme",
                 @"Pretty Woman Main Theme",
                 @"Pulp Fiction Movie",
                 @"Rawhide Theme",
                 @"Reservoir Dogs",
                 @"Return To The Future Main Theme",
                 @"Robin Hood Prince Of Thieves",
                 @"Rocky Theme",
                 @"Seinfeld Theme",
                 @"Sesame Theme",
                 @"Sex And The City",
                 @"Simply Tarantino",
                 @"Sons Of Anarchy Theme",
                 @"Space Jam Silver Screen",
                 @"Spiderman Theme",
                 @"Sponge Bob Theme",
                 @"Star Trek Theme",
                 @"Star Wars",
                 @"Star Wars Theme",
                 @"Superman Main Theme",
                 @"Superman Theme",
                 @"Teenage Mutant Ninja Turtles Theme",
                 @"The A-Team Main Theme",
                 @"The Addams Family",
                 @"The Bodyguard",
                 @"The Brady Bunch Theme",
                 @"The Flintstones Theme",
                 @"The Godfather",
                 @"The Good, The Bad And The Ugly Main Theme",
                 @"The River Kwai Theme",
                 @"The Simpsons",
                 @"The Terminator Main Theme",
                 @"The Walking Dead",
                 @"Three'S Company Theme",
                 @"Titanic",
                 @"Top Gun",
                 @"Toy Story",
                 @"True Detective Main Theme",
                 @"Walker Texas Ranger Theme",
                 @"X-Files Main Theme"
                 ];
    } else if ([genre  isEqual: @"Random"]) {
        return @[@"A Thousand Horses",
                 @"Andy Grammer",
                 @"Ariana Grande",
                 @"Bandit Gang Marco ",
                 @"Big Sean Feat Drake",
                 @"Billy Currington",
                 @"Blake Shelton",
                 @"Brad Paisley",
                 @"Brantley Gilbert",
                 @"Bruno Mars",
                 @"Calvin Harris",
                 @"Canaan Smith",
                 @"Carly Rae Jepsen",
                 @"Carrie Underwood",
                 @"Chedda Da Connect",
                 @"Chris Brown",
                 @"Ciara",
                 @"Cole Swindell",
                 @"David Guetta",
                 @"Dierks Bentley",
                 @"Dillon Francis",
                 @"Dj Snake",
                 @"Drake",
                 @"Easton Corbin",
                 @"Echosmith",
                 @"Ed Sheeran",
                 @"Ellie Goulding",
                 @"Eminem",
                 @"Eric Church",
                 @"Eric Paslay",
                 @"Fall Out Boy",
                 @"Fetty Wap",
                 @"Fifth Harmony",
                 @"Flo Rida ",
                 @"Florida Georgia Line",
                 @"Future",
                 @"George Ezra",
                 @"Hozier",
                 @"Iggy Azalea",
                 @"J.Cole",
                 @"Jason Aldean ",
                 @"Jason Derulo",
                 @"Jennifer Lopez",
                 @"Josh Groban",
                 @"Justin Bieber",
                 @"Justin Timberlake",
                 @"Kanye West",
                 @"Keith Urban",
                 @"Kelly Clarkson",
                 @"Kelsea Ballerini",
                 @"Kendrick Lamar",
                 @"Kenny Chesney",
                 @"Kevin Gates",
                 @"Kid Ink",
                 @"Little Big Town",
                 @"Luke Bryan",
                 @"Major Lazer",
                 @"Mariah Carey",
                 @"Mark Ronson",
                 @"Maroon 5",
                 @"Martin Garrix",
                 @"Meghan Trainor",
                 @"Mumford & Sons",
                 @"Natalie La Rose",
                 @"Nate Ruess",
                 @"Ne-Yo",
                 @"Nick Jonas",
                 @"Nicki Minaj",
                 @"Nicky Jam",
                 @"Omarion ",
                 @"Omi",
                 @"One Direction",
                 @"One Republic",
                 @"Pharrell Williams",
                 @"Pitbull ",
                 @"Psy",
                 @"Rachel Platten",
                 @"Rae Sremmurd",
                 @"Rich Homie Quan",
                 @"Rihanna",
                 @"Sam Hunt",
                 @"Sam Smith",
                 @"Sawyer Fredricks",
                 @"Sheppard",
                 @"Sia",
                 @"Silento",
                 @"Skrillex & Diplo",
                 @"T- Wayne",
                 @"The Weekend",
                 @"Tom Mcgraw",
                 @"Tori Kelly",
                 @"Tove Lo",
                 @"Trey Songz",
                 @"Twenty One Pilots",
                 @"Tyler Farr",
                 @"Wale",
                 @"Walk The Moon",
                 @"Wiz Khalifa",
                 @"X Ambassadors",
                 @"Zac Brown Band",
                 @"Zedd"
                 ];
    } else if ([genre  isEqual: @"Humor"]) {
        return @[@"Weird Al Yankovic - Eat It",
                 @"Weird Al Yankovic - Lame Claim To Fame",
                 @"Weird Al Yankovic - Lasagna",
                 @"Weird Al Yankovic - Like A Surgeon",
                 @"Weird Al Yankovic - White & Nerdy",
                 @"99 Words For Boobs",
                 @"Amy Schumer - Cockblock",
                 @"Amy Schumer - Miami, The Jewish",
                 @"Ass Whoopin Fuck Ringtone",
                 @"Aziz Ansari - Talking To Girls At",
                 @"Aziz Ansari - Texting With Girls ",
                 @"Bad Sex Taryn ",
                 @"Big Sean - I Don'T Fuck With You",
                 @"Bo Burnham - From God'S Perspective",
                 @"Bo Burnham - Left Brain, Right Brain",
                 @"Bo Burnham - My Whole Family…",
                 @"Boys A Faggot Rington",
                 @"Bugs Bunny - This Is Life?",
                 @"Bunch Of Whores Rington",
                 @"Burp Sound",
                 @"Chris Rock - Affirmative Action",
                 @"Chris Rock - Don'T Cheat",
                 @"Chris Rock - Drugs, Donuts ",
                 @"Chris Rock - Off The Pole",
                 @"Chris Rock - Rap Standup",
                 @"Chris Rock - Taxes",
                 @"Coffee Makes Me Poo",
                 @"Connoisseur Of Girl Tv",
                 @"E.T Fuck You Rington",
                 @"E.T. Child Molester Rington",
                 @"E.T. Wants Pussy Rington",
                 @"Eddie Griffin - Freedom Is A",
                 @"Eddie Griffin - Grandma'S Home",
                 @"Eddie Griffin - Tiger Woods",
                 @"Eddie Griffin - Viagra",
                 @"Eddie Murphy - Modern Women - Live",
                 @"Eddie Murphy - Skeleton In Closet",
                 @"Everyone Else Is An Asshole",
                 @"Frankly My Nigga Rington",
                 @"Get Fucked Up Rington",
                 @"Guys They Just Wanna $",
                 @"Hilarious Hit Makers - America",
                 @"Hilarious Hit Makers - Eat",
                 @"Hilarious Hit Makers - Hanukah Song",
                 @"Hilarious Hit Makers - United States",
                 @"Hilarious Hit Makers - Your Mother's Got A Penis",
                 @"I Peed In The Pool",
                 @"I Think I Farted",
                 @"Infant Sorrow - I Am Jesus",
                 @"Jerky Boys",
                 @"Jerky Boyz Laser Surgery",
                 @"Joke. 50 Funny Sounds",
                 @"Jon Lajoie - Everyday Normal Guy 2",
                 @"Jon Lajoie - I Kill People",
                 @"Jon Lajoie - Show Me Your",
                 @"Just Google That Shit",
                 @"Keep In Your Pants",
                 @"Kevin Hart - Good Mood",
                 @"Knonk Knock Jokes",
                 @"Lois - Quahog  Holiday",
                 @"Loser Hip Hop Rington",
                 @"Louis C.K. - I Hate Deer",
                 @"Louis C.K. - Intro/ Dead People",
                 @"Louis C.K. - Milk & Pets",
                 @"Louis C.K. - Taking Sexual ",
                 @"Luke I Fucked Your Mother Rington",
                 @"Mark Normand - Jews",
                 @"Monty Python - Every Sperm Is",
                 @"Monty Python - Never Be Rude To An ",
                 @"Monty Python - Penis Song",
                 @"Monty Python - Sit On My Face",
                 @"Nice Peter - Darth Vader",
                 @"Pig Farmer - Asshole!",
                 @"Rappy Mcrapperson - Gigantic Vagina",
                 @"Rappy Mcrapperson - Lyobpd",
                 @"Rappy Mcrapperson - Planet Lesbodian",
                 @"Re: Your Song About Me",
                 @"Red Peters 2Fat2F***",
                 @"Red Peters Bonus Track",
                 @"Red Peters Do You Take It In The Ass",
                 @"Red Peters Fuck The Shit",
                 @"Red Peters Fuck You",
                 @"Red Peters He'S An A******",
                 @"Red Peters Holy Sh*T, It'S",
                 @"Red Peters I Gotta Take A",
                 @"Red Peters The Hand",
                 @"Red Peters Unwanted Rock",
                 @"Red Peters Vagina",
                 @"Red Peters Will You Swallow My",
                 @"Red Peters You Ain'T Getting Sh*T",
                 @"Robin Williams - Bush, Cheney",
                 @"Robin Williams - Drugs, Alcoholism",
                 @"Robin Williams - Fires, Weed And The",
                 @"Rodney Carrington - Letter To My Penis",
                 @"Sarah Silverman - Goodnight",
                 @"Sarah Silverman - Head Off My Titties",
                 @"Sarah Silverman - Killing Jesus",
                 @"Sarah Silverman - Poop Song",
                 @"Save Your Ballsack",
                 @"Sir Mix A Lot",
                 @"The Awful Truth About Hannah Montana",
                 @"The Closing Song Red Peters",
                 @"The Lonely Island - Dick In A Box",
                 @"The Lonely Island - I Just Had Sex",
                 @"The Lonely Island - I'M On A Boat",
                 @"The Lonely Island - Jizz",
                 @"The Lonely Island - Like A Boss",
                 @"The Lonely Island - Spring Break Anthem",
                 @"The Star Wars Chanukah Song",
                 @"The Toilet Bowl Cleaners - Justin",
                 @"The Toilet Bowl Cleaners - The Butt Song",
                 @"The Toilet Bowl Cleaners - The Fart Song",
                 @"The Toilet Bowl Cleaners - The Poop Song",
                 @"Tom Hanks Is An Asshole",
                 @"Touch Your Boobies",
                 @"Ultimate Fart",
                 @"Where Is My Goat",
                 @"Wrong Hole: The Untold"
                 ];
    } else {
        return @[@"Error"];
    }

    return @[];
}

@end
