//
//  SpotifyArtistFactory.m
//  YapTap
//
//  Created by Jon Deokule on 5/2/15.
//  Copyright (c) 2015 Appcoda. All rights reserved.
//

#import "SpotifyArtistFactory.h"

@implementation SpotifyArtistFactory

+ (NSArray *) artistsForGenre:(NSString *)genre
{
    if ([genre  isEqual: @"Pop"]) {
        return @[@"Abba",
                 @"Adam Lambert",
                 @"Adele",
                 @"Amy Winehouse",
                 @"Andreas Roffler",
                 @"Ariana Grande",
                 @"Ark Patrol",
                 @"Astronauts",
                 @"Backstreet Boys",
                 @"Bastille",
                 @"Beth Love",
                 @"Beyonce",
                 @"Big Sean",
                 @"Blackbear",
                 @"Blue October",
                 @"Brayton Bowman",
                 @"Britney Spears",
                 @"Broken Back",
                 @"Bruce Springsteen",
                 @"Bruno Mars",
                 @"Cashmere Cat",
                 @"Charlie Puth",
                 @"Christina Aguilera",
                 @"Christina Perri",
                 @"Coldpay",
                 @"Darius",
                 @"Dawin",
                 @"Devon Baldwin",
                 @"Dj Earworm",
                 @"Dj Midnight",
                 @"Duran Duran",
                 @"Eagles",
                 @"Ed Sheeran",
                 @"Ellie Goulding",
                 @"Elton John",
                 @"Elvis Presley",
                 @"Fantasia",
                 @"Fergie",
                 @"Glee",
                 @"Halvorsen",
                 @"Honne",
                 @"Hozier",
                 @"Hyphy Da Spider",
                 @"I Love Makonnen",
                 @"I Prevail",
                 @"Idina Menzel",
                 @"Jack Ü",
                 @"Janet Jackson",
                 @"Jennifer Lopez ",
                 @"Jessie J",
                 @"John Legend",
                 @"Josh Groban",
                 @"Justin Bieber",
                 @"Kaskade",
                 @"Katy Perry",
                 @"Lady Gaga",
                 @"Madonna",
                 @"Manganas Garden",
                 @"Mariah Carey",
                 @"Mark Ronson",
                 @"Maroon 5",
                 @"Marvin Gaye 50",
                 @"Max Feat Hoodie",
                 @"Meghan Trainor",
                 @"Michael Jackson",
                 @"Miley Cyrus",
                 @"Nick Jonas",
                 @"Nsync",
                 @"Oh Wonder",
                 @"One Direction",
                 @"Penguin Prison",
                 @"Pet Shop Boys",
                 @"Phoebe Ryan",
                 @"Pitbull Chris Brown",
                 @"Prince",
                 @"Psy",
                 @"R Kelly",
                 @"Rae Sremmurd",
                 @"Rihanna",
                 @"Robbie Williams",
                 @"Sam Cooke",
                 @"Sam Smith",
                 @"Selena Gomez",
                 @"Shawn Mendes",
                 @"Sia",
                 @"Simon And Garfunkel",
                 @"Skrillex",
                 @"Spice Girls",
                 @"Sterkol",
                 @"Steve Aoki",
                 @"Stevie Wonder",
                 @"Take Me To Chruch",
                 @"Tep No",
                 @"The Beatles",
                 @"The Black Eyed Peas",
                 @"The Drums",
                 @"The Eden Project",
                 @"The Weekend",
                 @"Tove Lo",
                 @"Trevor Wesley",
                 @"U2",
                 @"Whitney Houston",
                 @"Xylo",
                 @"Zyan Malik"
                 ];
    } else if ([genre  isEqual: @"Hip Hop"]) {
        return @[@"2Pac",
                 @"50 Cent",
                 @"Akon",
                 @"Bandit Gang Marco",
                 @"Beastie Boys",
                 @"Beyonce",
                 @"Big Sean",
                 @"Blackstreet",
                 @"Busta Rhymes",
                 @"Chedda Da Connect",
                 @"Chris Brown",
                 @"Ciara",
                 @"Coolio",
                 @"Cypress Hill",
                 @"Dead Prez",
                 @"Dj Kool",
                 @"Dmx",
                 @"Dr. Dre",
                 @"Drake",
                 @"Eminem",
                 @"Fetty Wap",
                 @"Flo Rida",
                 @"Fugees",
                 @"Grandmaster Flash",
                 @"House Of Pain",
                 @"Ice Cube",
                 @"Iggy Azalea",
                 @"J. Cole",
                 @"Ja Rule ",
                 @"Jason Derulo",
                 @"Jay Z",
                 @"Jeremih",
                 @"Jidenna",
                 @"Joey Bada$$",
                 @"Juicy J ",
                 @"Justin Timberlake",
                 @"K Camp",
                 @"Kanye West",
                 @"Kendrick Lamar",
                 @"Kevin Gates",
                 @"Kid Ink",
                 @"Lauryn Hill",
                 @"Lil Wayne",
                 @"Ll Cool J",
                 @"Ludacris",
                 @"Luniz",
                 @"Migos",
                 @"Missy Elliot",
                 @"N.W.A",
                 @"Nas",
                 @"Natalie La Rose ",
                 @"Nate Dogg",
                 @"Ne-Yo",
                 @"Nelly",
                 @"Nicki Minaj",
                 @"Notorious B.I.G.",
                 @"Omarion",
                 @"Outkast",
                 @"Pharrell",
                 @"Pitbull",
                 @"Public Enemy",
                 @"Puff Daddy",
                 @"Rae Sremmurd",
                 @"Rich Homie Quan",
                 @"Rick Ross",
                 @"Rihanna",
                 @"Run D.M.C",
                 @"Salt-N-Pepa",
                 @"Schoolboy Q",
                 @"Silento",
                 @"Sir Mix A Lot",
                 @"Sisqo",
                 @"Snoop Dog",
                 @"Soulja Boy",
                 @"Swedish House Pussy",
                 @"T-Wayne",
                 @"T.I",
                 @"Talib Kweli",
                 @"That'S My Shit",
                 @"The Black Eyed Peas",
                 @"The Rapsody",
                 @"The-Dream",
                 @"Tinashe",
                 @"Tone-Loc",
                 @"Trey Songz",
                 @"Tyga",
                 @"Usher",
                 @"Vanilla Ice",
                 @"Wale",
                 @"Warren G",
                 @"Wiz Khalifa",
                 @"Wu-Tang Clan",
                 @"Yelawolf"
                 ];
    } else if ([genre  isEqual: @"Rock"]) {
        return @[@"Ac/Dc",
                 @"Aerosmith",
                 @"Alabama Shakes",
                 @"Alice Cooper",
                 @"Awolnation",
                 @"Billy Idol",
                 @"Billy Joel",
                 @"Black Sabbath",
                 @"Blink 182",
                 @"Bob Dylan",
                 @"Bon Jovi",
                 @"Breaking Benjamin",
                 @"Bruce Springsteen",
                 @"Cat Stevens",
                 @"Coldplay",
                 @"Cream",
                 @"Creedence Clearwater Revival",
                 @"David Bowie",
                 @"Death Cab For Cutie",
                 @"Deep Purple",
                 @"Dire Straits",
                 @"Don Henley",
                 @"Eagles",
                 @"Eddie Veder",
                 @"Elvis Presley",
                 @"Eric Clapton",
                 @"Europe",
                 @"Evanescence",
                 @"Fall Out Boy",
                 @"Florence + The Machine",
                 @"Foo Fighteres",
                 @"George Ezra",
                 @"Goo Goo Dolls",
                 @"Green Day",
                 @"Guns N' Roses",
                 @"Hozier",
                 @"Iggy Pop",
                 @"Iron Maiden",
                 @"James Bay",
                 @"Jimi Hendrix",
                 @"John Lennon",
                 @"Journey",
                 @"Kiss",
                 @"Led Zeppelin",
                 @"Lenny Kravitz",
                 @"Limp Bizkit",
                 @"Linkin Park",
                 @"Lou Reed",
                 @"Lynyrd Skynyrd",
                 @"Mailyn Manson",
                 @"Matt Mcandrew",
                 @"Metallica",
                 @"Mumford & Sons",
                 @"Muse",
                 @"Nate Ruess",
                 @"Needtobreathe",
                 @"Neil Young",
                 @"Nickelback",
                 @"Nirvana",
                 @"Offspring",
                 @"Ozzy Osbourne",
                 @"Panic! At The Disco",
                 @"Papa Roach",
                 @"Paul Mccartney",
                 @"Pearl Jam",
                 @"Phil Collins",
                 @"Pink Floyd",
                 @"Prince",
                 @"Queen",
                 @"R.E.M",
                 @"Rage Against The Machine",
                 @"Red Hot Chili Peppers",
                 @"Royal Blood",
                 @"Santana",
                 @"Sawyer Fredericks",
                 @"Scorpions",
                 @"Simon & Garfunkel",
                 @"Stealers Wheel",
                 @"Sting",
                 @"Survivor",
                 @"System Of A Down",
                 @"The Animals",
                 @"The Beatles",
                 @"The Doors",
                 @"The Kinks",
                 @"The Mamas & The Papas",
                 @"The Police",
                 @"The Rolling Stones",
                 @"The White Stripes",
                 @"The Who",
                 @"Twenty One Pilots",
                 @"U2",
                 @"Van Halen",
                 @"Walk The Moon ",
                 @"X Ambassadors",
                 @"Zac Brown Band"
                 ];
    } else if ([genre  isEqual: @"EDM"]) {
        return @[@"1200 Micrograms",
                 @"Ace Ventura",
                 @"Afrojack",
                 @"Alesso",
                 @"Alien Project",
                 @"Armin Van Buuren",
                 @"Astral Projection",
                 @"Astrix",
                 @"Atb",
                 @"Avicii",
                 @"Axwell",
                 @"Axwell^Ingrosso",
                 @"Bassjackers",
                 @"Bingo Players",
                 @"Blasterjaxx",
                 @"Bynon",
                 @"Calvin Harris",
                 @"Cosma",
                 @"Dada Life",
                 @"Dannic",
                 @"Dannic",
                 @"David Guetta",
                 @"Deorro",
                 @"Dillon Francis",
                 @"Dimitri Vangelis",
                 @"Dimitri Vegas",
                 @"Dirty Ducks",
                 @"Dvbbs",
                 @"Eelke Kleijn",
                 @"Eyal Barkan",
                 @"Fedde Le Gran",
                 @"Feder",
                 @"Flatdisk",
                 @"Ftampa",
                 @"Galantis",
                 @"Galantis",
                 @"Gms",
                 @"Hardwell",
                 @"Headhunterz",
                 @"Infected Mushroom",
                 @"Ivan Gough & Feenixpawl",
                 @"Joey Dale ",
                 @"John Alexander",
                 @"John Newman",
                 @"Kaskade",
                 @"Kura",
                 @"Kygo",
                 @"Kygo",
                 @"Laidback Luke",
                 @"Lost Frequencies",
                 @"Lucky Date",
                 @"Made In June",
                 @"Madeon",
                 @"Major Lazer",
                 @"Marc Benjamin",
                 @"Marnik",
                 @"Martin Garrix",
                 @"Martin Jensen",
                 @"Martin Solveig",
                 @"Martin Tungevaag",
                 @"Mason",
                 @"Mason",
                 @"Mr. Probz",
                 @"Mydo",
                 @"Nervo",
                 @"Nicky Romero",
                 @"Oceanlab",
                 @"Otto Knows",
                 @"Paul Van Dyk",
                 @"Pelari ",
                 @"Revolvr",
                 @"Ritmo",
                 @"Rune Rk",
                 @"Sabastian Sollerman",
                 @"Sander Van Doorn",
                 @"Showtek",
                 @"Sick Individuals",
                 @"Skazi",
                 @"Skitzofrenix",
                 @"Space Cat",
                 @"Steve Aoki",
                 @"Swedish House Mafia",
                 @"Talamasca",
                 @"The Double Drop",
                 @"Thomas Gold",
                 @"Thomas Newson",
                 @"Tiesto",
                 @"Tjr",
                 @"Tom & Jame",
                 @"Tommy Trash",
                 @"Twoloud",
                 @"Voodoo People",
                 @"X-Dream",
                 @"Yahel",
                 @"Yellow Claw",
                 @"Young Squage",
                 @"Younger Brother",
                 @"Yves V",
                 @"Zedd"
                 ];
    } else if ([genre  isEqual: @"Country"]) {
        return @[@"A Thousand Horses",
                 @"Billy Currington",
                 @"Blake Shelton",
                 @"Brad Paisley",
                 @"Brantley Gilbert",
                 @"Brett Eldredge",
                 @"Canaan Smith",
                 @"Carrie Underwood",
                 @"Casey James",
                 @"Charlie Worsham",
                 @"Chris Young",
                 @"Cole Swindell",
                 @"Craig Campbell",
                 @"Darius Rucker",
                 @"Dierks Bentley",
                 @"Easton Corbin",
                 @"Eric Church",
                 @"Eric Paslay",
                 @"Florida Georgia Line",
                 @"Frankie Ballard",
                 @"Gary Allan",
                 @"George Straits",
                 @"Hunter Hayes",
                 @"Jason Aldean",
                 @"Joe Nicholas",
                 @"Justin Moore",
                 @"Kacey Musgraves",
                 @"Keith Urban Featuring Eric Church",
                 @"Kelsea Ballerini",
                 @"Kenny Chesney With Grace Potter",
                 @"Kip Moore",
                 @"Lady Antebellum",
                 @"Lee Brice",
                 @"Little Big Town",
                 @"Luke Bryan",
                 @"Michael Ray",
                 @"Miranda Lambert",
                 @"Omarion ",
                 @"Parmalee",
                 @"Randy Houser ",
                 @"Rascal Flatts",
                 @"Sam Hunt",
                 @"The Band Perry",
                 @"Thompson Square",
                 @"Tim Mcgraw With Catherine Dunn",
                 @"Train Feat Ashley",
                 @"Tyler Farr",
                 @"Zac Brown Band"
                 ];
    } else if ([genre  isEqual: @"TV/Film"]) {
        return @[@"The Rocky Horror Picture Show",
                 @"100 Movie Themes",
                 @"24 Main Theme",
                 @"300 Soundtrack",
                 @"Aladdin Theme",
                 @"Austin Powers Theme",
                 @"Back To The FutureTheme",
                 @"Batman Theme",
                 @"Baywatch",
                 @"Beverly Hills 90210",
                 @"Beverly Hills Cop Theme",
                 @"Bill Conti ",
                 @"Breakfast Club",
                 @"Breaking Bad Theme",
                 @"Bugs Bunny",
                 @"Call Of Duty",
                 @"Chanukah Song",
                 @"Columbo Theme",
                 @"Dallas",
                 @"Dexter Theme",
                 @"Django",
                 @"Doctor Who Theme",
                 @"E.T Theme",
                 @"Family Guy Main Theme",
                 @"Family Matters Theme",
                 @"Fifa",
                 @"Free Willy",
                 @"Fresh Prince Of Bel-Air ",
                 @"Game Of Thrones Main Theme",
                 @"Ghostbusters Dance",
                 @"Hannah Montana Theme",
                 @"Hilarious Hit Makers - Muppet Show",
                 @"Home Alone Theme",
                 @"Hooked Of A Feeling",
                 @"I’Ll Be There For You",
                 @"Indiana Jones Theme",
                 @"Inspector Gadget Theme",
                 @"James Bond Skyfall",
                 @"James Bond Theme",
                 @"Jaws Theme",
                 @"Kill Bill",
                 @"Kill Bill Whistle Theme",
                 @"Law And Order Theme",
                 @"Lion King",
                 @"Lost Main Theme",
                 @"Love Boat Theme",
                 @"Mac Gyver Main Theme",
                 @"Mission Impossible",
                 @"Monday Night Football Theme",
                 @"Nba Espn",
                 @"Patton Theme",
                 @"Peanuts Theme",
                 @"Pinky And The Brain Theme",
                 @"Pirates Of The Caribbean Theme",
                 @"Pretty Woman Main Theme",
                 @"Pulp Fiction Movie",
                 @"Rawhide Theme",
                 @"Reservoir Dogs",
                 @"Return To The Future Main Theme",
                 @"Robin Hood Prince Of Thieves",
                 @"Rocky Theme",
                 @"Seinfeld Theme",
                 @"Sesame Theme",
                 @"Sex And The City",
                 @"Simply Tarantino",
                 @"Sons Of Anarchy Theme",
                 @"Space Jam Silver Screen",
                 @"Spiderman Theme",
                 @"Sponge Bob Theme",
                 @"Star Trek Theme",
                 @"Star Wars",
                 @"Star Wars Theme",
                 @"Superman Main Theme",
                 @"Superman Theme",
                 @"Teenage Mutant Ninja Turtles Theme",
                 @"The A-Team Main Theme",
                 @"The Addams Family",
                 @"The Bodyguard",
                 @"The Brady Bunch Theme",
                 @"The Flintstones Theme",
                 @"The Godfather",
                 @"The Good, The Bad And The Ugly Main Theme",
                 @"The River Kwai Theme",
                 @"The Simpsons",
                 @"The Terminator Main Theme",
                 @"The Walking Dead",
                 @"Three'S Company Theme",
                 @"Titanic",
                 @"Top Gun",
                 @"Toy Story",
                 @"True Detective Main Theme",
                 @"Walker Texas Ranger Theme",
                 @"X-Files Main Theme"
                 ];
    } else if ([genre  isEqual: @"Top 100"]) {
        return @[@"A Thousand Horses",
                 @"Andy Grammer",
                 @"Ariana Grande",
                 @"Bandit Gang Marco ",
                 @"Big Sean Feat Drake",
                 @"Billy Currington",
                 @"Blake Shelton",
                 @"Brad Paisley",
                 @"Brantley Gilbert",
                 @"Bruno Mars",
                 @"Calvin Harris",
                 @"Canaan Smith",
                 @"Carly Rae Jepsen",
                 @"Carrie Underwood",
                 @"Chedda Da Connect",
                 @"Chris Brown",
                 @"Ciara",
                 @"Cole Swindell",
                 @"David Guetta",
                 @"Dierks Bentley",
                 @"Dillon Francis",
                 @"Dj Snake",
                 @"Drake",
                 @"Easton Corbin",
                 @"Echosmith",
                 @"Ed Sheeran",
                 @"Ellie Goulding",
                 @"Eminem",
                 @"Eric Church",
                 @"Eric Paslay",
                 @"Fall Out Boy",
                 @"Fetty Wap",
                 @"Fifth Harmony",
                 @"Flo Rida ",
                 @"Florida Georgia Line",
                 @"Future",
                 @"George Ezra",
                 @"Hozier",
                 @"Iggy Azalea",
                 @"J.Cole",
                 @"Jason Aldean ",
                 @"Jason Derulo",
                 @"Jennifer Lopez",
                 @"Josh Groban",
                 @"Justin Bieber",
                 @"Justin Timberlake",
                 @"Kanye West",
                 @"Keith Urban",
                 @"Kelly Clarkson",
                 @"Kelsea Ballerini",
                 @"Kendrick Lamar",
                 @"Kenny Chesney",
                 @"Kevin Gates",
                 @"Kid Ink",
                 @"Little Big Town",
                 @"Luke Bryan",
                 @"Major Lazer",
                 @"Mariah Carey",
                 @"Mark Ronson",
                 @"Maroon 5",
                 @"Martin Garrix",
                 @"Meghan Trainor",
                 @"Mumford & Sons",
                 @"Natalie La Rose",
                 @"Nate Ruess",
                 @"Ne-Yo",
                 @"Nick Jonas",
                 @"Nicki Minaj",
                 @"Nicky Jam",
                 @"Omarion ",
                 @"Omi",
                 @"One Direction",
                 @"One Republic",
                 @"Pharrell Williams",
                 @"Pitbull ",
                 @"Psy",
                 @"Rachel Platten",
                 @"Rae Sremmurd",
                 @"Rich Homie Quan",
                 @"Rihanna",
                 @"Sam Hunt",
                 @"Sam Smith",
                 @"Sawyer Fredricks",
                 @"Sheppard",
                 @"Sia",
                 @"Silento",
                 @"Skrillex & Diplo",
                 @"T- Wayne",
                 @"The Weekend",
                 @"Tom Mcgraw",
                 @"Tori Kelly",
                 @"Tove Lo",
                 @"Trey Songz",
                 @"Twenty One Pilots",
                 @"Tyler Farr",
                 @"Wale",
                 @"Walk The Moon",
                 @"Wiz Khalifa",
                 @"X Ambassadors",
                 @"Zac Brown Band",
                 @"Zedd"
                 ];
    } else if ([genre  isEqual: @"Latin"]) {
        return @[@"Ariel Camacho Y Los Plebes Del Rancho",
                 @"Ariel Camacho Y Los Plebes Del Rancho",
                 @"Banda El Recodo De Cruz Lizarraga",
                 @"Banda Los Recoditos",
                 @"Banda Sinaloense Ms De Sergio Lizarraga",
                 @"Banda Sinaloense Ms De Sergio Lizarraga",
                 @"Calibre 50",
                 @"Chayanne",
                 @"Chino & Nacho",
                 @"Chiquis Rivera",
                 @"Daddy Yankee",
                 @"Daddy Yankee, Lil Jon, Noriega & Pitbull",
                 @"Denise De Kalafe",
                 @"Denise De Kalafe",
                 @"Don Omar",
                 @"Don Omar & Lucenzo",
                 @"El Komander",
                 @"Elvis Crespo",
                 @"Enrique Iglesias",
                 @"Farruko",
                 @"Fito Blanko",
                 @"Gente De Zona La",
                 @"Gerardo Ortíz",
                 @"Gerardo Ortíz",
                 @"J Balvin",
                 @"Jeniffer Lopez A Selena Tribute",
                 @"Jory Boy",
                 @"Juanes",
                 @"Julion Alvarez Y Su Norteño Banda",
                 @"Julion Alvarez Y Su Norteño Banda",
                 @"Los Del Río",
                 @"Los Tigres Del Norte",
                 @"Maluma",
                 @"Maná Mi",
                 @"Marc Anthony",
                 @"Marco Antonio Solís & Los Bukis",
                 @"Natalia Jiménez",
                 @"Nicky Jam",
                 @"Osmani Garcia",
                 @"Pitbull",
                 @"Plan B Fanatica",
                 @"Prince Royce",
                 @"Prince Royce",
                 @"Ricky Martin",
                 @"Romeo Santos",
                 @"Santana",
                 @"Selena",
                 @"Shakira",
                 @"Tony Dize",
                 @"Vicente Fernández",
                 @"Wisin",
                 @"Wisin & Carlos Vives",
                 @"Xtreme",
                 @"Zion Y Lennox"
                 ];
    } else if ([genre  isEqual: @"Humor"]) {
        return @[@"Weird Al Yankovic - Eat It",
                 @"Weird Al Yankovic - Lame Claim To Fame",
                 @"Weird Al Yankovic - Lasagna",
                 @"Weird Al Yankovic - Like A Surgeon",
                 @"Weird Al Yankovic - White & Nerdy",
                 @"99 Words For Boobs",
                 @"Amy Schumer - Cockblock",
                 @"Amy Schumer - Miami, The Jewish",
                 @"Ass Whoopin Fuck Ringtone",
                 @"Aziz Ansari - Talking To Girls At",
                 @"Aziz Ansari - Texting With Girls ",
                 @"Bad Sex Taryn ",
                 @"Big Sean - I Don'T Fuck With You",
                 @"Bo Burnham - From God'S Perspective",
                 @"Bo Burnham - Left Brain, Right Brain",
                 @"Bo Burnham - My Whole Family…",
                 @"Boys A Faggot Rington",
                 @"Bugs Bunny - This Is Life?",
                 @"Bunch Of Whores Rington",
                 @"Burp Sound",
                 @"Chris Rock - Affirmative Action",
                 @"Chris Rock - Don'T Cheat",
                 @"Chris Rock - Drugs, Donuts ",
                 @"Chris Rock - Off The Pole",
                 @"Chris Rock - Rap Standup",
                 @"Chris Rock - Taxes",
                 @"Coffee Makes Me Poo",
                 @"Connoisseur Of Girl Tv",
                 @"E.T Fuck You Rington",
                 @"E.T. Child Molester Rington",
                 @"E.T. Wants Pussy Rington",
                 @"Eddie Griffin - Freedom Is A",
                 @"Eddie Griffin - Grandma'S Home",
                 @"Eddie Griffin - Tiger Woods",
                 @"Eddie Griffin - Viagra",
                 @"Eddie Murphy - Modern Women - Live",
                 @"Eddie Murphy - Skeleton In Closet",
                 @"Everyone Else Is An Asshole",
                 @"Frankly My Nigga Rington",
                 @"Get Fucked Up Rington",
                 @"Guys They Just Wanna $",
                 @"Hilarious Hit Makers - America",
                 @"Hilarious Hit Makers - Eat",
                 @"Hilarious Hit Makers - Hanukah Song",
                 @"Hilarious Hit Makers - United States",
                 @"Hilarious Hit Makers - Your Mother's Got A Penis",
                 @"I Peed In The Pool",
                 @"I Think I Farted",
                 @"Infant Sorrow - I Am Jesus",
                 @"Jerky Boys",
                 @"Jerky Boyz Laser Surgery",
                 @"Joke. 50 Funny Sounds",
                 @"Jon Lajoie - Everyday Normal Guy 2",
                 @"Jon Lajoie - I Kill People",
                 @"Jon Lajoie - Show Me Your",
                 @"Just Google That Shit",
                 @"Keep In Your Pants",
                 @"Kevin Hart - Good Mood",
                 @"Knonk Knock Jokes",
                 @"Lois - Quahog  Holiday",
                 @"Loser Hip Hop Rington",
                 @"Louis C.K. - I Hate Deer",
                 @"Louis C.K. - Intro/ Dead People",
                 @"Louis C.K. - Milk & Pets",
                 @"Louis C.K. - Taking Sexual ",
                 @"Luke I Fucked Your Mother Rington",
                 @"Mark Normand - Jews",
                 @"Monty Python - Every Sperm Is",
                 @"Monty Python - Never Be Rude To An ",
                 @"Monty Python - Penis Song",
                 @"Monty Python - Sit On My Face",
                 @"Nice Peter - Darth Vader",
                 @"Pig Farmer - Asshole!",
                 @"Rappy Mcrapperson - Gigantic Vagina",
                 @"Rappy Mcrapperson - Lyobpd",
                 @"Rappy Mcrapperson - Planet Lesbodian",
                 @"Re: Your Song About Me",
                 @"Red Peters 2Fat2F***",
                 @"Red Peters Bonus Track",
                 @"Red Peters Do You Take It In The Ass",
                 @"Red Peters Fuck The Shit",
                 @"Red Peters Fuck You",
                 @"Red Peters He'S An A******",
                 @"Red Peters Holy Sh*T, It'S",
                 @"Red Peters I Gotta Take A",
                 @"Red Peters The Hand",
                 @"Red Peters Unwanted Rock",
                 @"Red Peters Vagina",
                 @"Red Peters Will You Swallow My",
                 @"Red Peters You Ain'T Getting Sh*T",
                 @"Robin Williams - Bush, Cheney",
                 @"Robin Williams - Drugs, Alcoholism",
                 @"Robin Williams - Fires, Weed And The",
                 @"Rodney Carrington - Letter To My Penis",
                 @"Sarah Silverman - Goodnight",
                 @"Sarah Silverman - Head Off My Titties",
                 @"Sarah Silverman - Killing Jesus",
                 @"Sarah Silverman - Poop Song",
                 @"Save Your Ballsack",
                 @"Sir Mix A Lot",
                 @"The Awful Truth About Hannah Montana",
                 @"The Closing Song Red Peters",
                 @"The Lonely Island - Dick In A Box",
                 @"The Lonely Island - I Just Had Sex",
                 @"The Lonely Island - I'M On A Boat",
                 @"The Lonely Island - Jizz",
                 @"The Lonely Island - Like A Boss",
                 @"The Lonely Island - Spring Break Anthem",
                 @"The Star Wars Chanukah Song",
                 @"The Toilet Bowl Cleaners - Justin",
                 @"The Toilet Bowl Cleaners - The Butt Song",
                 @"The Toilet Bowl Cleaners - The Fart Song",
                 @"The Toilet Bowl Cleaners - The Poop Song",
                 @"Tom Hanks Is An Asshole",
                 @"Touch Your Boobies",
                 @"Ultimate Fart",
                 @"Where Is My Goat",
                 @"Wrong Hole: The Untold"
                 ];
    } else {
        return @[@"Error"];
    }

    return @[];
}

@end
